package simhash

import (
	"strings"
)

var stopWordsByLanguage = map[string]map[string]bool{
	"ENGLISH":   {},
	"HINDI":     {},
	"TAMIL":     {},
	"TELUGU":    {},
	"KANNADA":   {},
	"MALAYALAM": {},
	"BENGALI":   {},
	"MARATHI":   {},
	"GUJARATI":  {},
	"ODIA":      {},
	"PUNJABI":   {},
}

func init() {
	// English stop words
	stopWordsByLanguage["ENGLISH"] = map[string]bool{
		"a": true, "about": true, "above": true, "after": true, "again": true, "against": true,
		"all": true, "am": true, "an": true, "and": true, "any": true, "are": true, "aren't": true,
		"as": true, "at": true, "be": true, "because": true, "been": true, "before": true,
		"being": true, "below": true, "between": true, "both": true, "but": true, "by": true,
		"can't": true, "cannot": true, "could": true, "couldn't": true, "did": true, "didn't": true,
		"do": true, "does": true, "doesn't": true, "doing": true, "don't": true, "down": true,
		"during": true, "each": true, "few": true, "for": true, "from": true, "further": true,
		"had": true, "hadn't": true, "has": true, "hasn't": true, "have": true, "haven't": true,
		"having": true, "he": true, "he'd": true, "he'll": true, "he's": true, "her": true,
		"here": true, "here's": true, "hers": true, "herself": true, "him": true, "himself": true,
		"his": true, "how": true, "how's": true, "i": true, "i'd": true, "i'll": true, "i'm": true,
		"i've": true, "if": true, "in": true, "into": true, "is": true, "isn't": true, "it": true,
		"it's": true, "its": true, "itself": true, "let's": true, "me": true, "more": true,
		"most": true, "mustn't": true, "my": true, "myself": true, "no": true, "nor": true,
		"not": true, "of": true, "off": true, "on": true, "once": true, "only": true, "or": true,
		"other": true, "ought": true, "our": true, "ours": true, "ourselves": true, "out": true,
		"over": true, "own": true, "same": true, "shan't": true, "she": true, "she'd": true,
		"she'll": true, "she's": true, "should": true, "shouldn't": true, "so": true, "some": true,
		"such": true, "than": true, "that": true, "that's": true, "the": true, "their": true,
		"theirs": true, "them": true, "themselves": true, "then": true, "there": true, "there's": true,
		"these": true, "they": true, "they'd": true, "they'll": true, "they're": true, "they've": true,
		"this": true, "those": true, "through": true, "to": true, "too": true, "under": true,
		"until": true, "up": true, "very": true, "was": true, "wasn't": true, "we": true,
		"we'd": true, "we'll": true, "we're": true, "we've": true, "were": true, "weren't": true,
		"what": true, "what's": true, "when": true, "when's": true, "where": true, "where's": true,
		"which": true, "while": true, "who": true, "who's": true, "whom": true, "why": true,
		"why's": true, "with": true, "won't": true, "would": true, "wouldn't": true, "you": true,
		"you'd": true, "you'll": true, "you're": true, "you've": true, "your": true, "yours": true,
		"yourself": true, "yourselves": true,
	}

	// Hindi stop words
	stopWordsByLanguage["HINDI"] = map[string]bool{
		"अत": true, "अपना": true, "अपनी": true, "अपने": true, "अभी": true, "अंदर": true,
		"आदि": true, "आप": true, "इत्यादि": true, "इस": true, "इसका": true, "इसकी": true,
		"इसके": true, "इसमें": true, "इसी": true, "इसे": true, "उन": true, "उनका": true,
		"उनकी": true, "उनके": true, "उनको": true, "उन्हें": true, "उन्हों": true, "उस": true,
		"उसका": true, "उसकी": true, "उसके": true, "उसको": true, "उसमें": true, "उसी": true,
		"उसे": true, "एक": true, "एवं": true, "एस": true, "ऐसे": true, "और": true, "कई": true,
		"कर": true, "करता": true, "करते": true, "करना": true, "करने": true, "करें": true,
		"कहते": true, "कहा": true, "का": true, "काफ़ी": true, "कि": true, "कितना": true,
		"किन्हें": true, "किन्हों": true, "किया": true, "किर": true, "किस": true, "किसी": true,
		"किसे": true, "की": true, "कुछ": true, "कुल": true, "के": true, "को": true, "कोई": true,
		"कौन": true, "कौनसा": true, "गया": true, "घर": true, "जब": true, "जहाँ": true, "जा": true,
		"जितना": true, "जिन": true, "जिन्हें": true, "जिन्हों": true, "जिस": true, "जिसे": true,
		"जीधर": true, "जैसा": true, "जैसे": true, "जो": true, "तक": true, "तब": true, "तरह": true,
		"तिन": true, "तिन्हें": true, "तिन्हों": true, "तिस": true, "तिसे": true, "तो": true,
		"था": true, "थी": true, "थे": true, "दबारा": true, "दिया": true, "दुसरा": true, "दूसरे": true,
		"दो": true, "द्वारा": true, "न": true, "नके": true, "नहीं": true, "ना": true, "निहायत": true,
		"नीचे": true, "ने": true, "पर": true, "पहले": true, "पूरा": true, "पे": true, "फिर": true,
		"बनी": true, "बही": true, "बहुत": true, "बाद": true, "बाला": true, "बिलकुल": true, "भी": true,
		"भीतर": true, "मगर": true, "मानो": true, "मे": true, "में": true, "यदि": true, "यह": true,
		"यहाँ": true, "यही": true, "या": true, "यिह": true, "ये": true, "रखें": true, "रहा": true,
		"रहे": true, "ऱ्वासा": true, "लिए": true, "लिये": true, "लेकिन": true, "व": true, "वग़ैरह": true,
		"वर्ग": true, "वह": true, "वहाँ": true, "वहीं": true, "वाले": true, "वुह": true, "वे": true,
		"सकता": true, "सकते": true, "सबसे": true, "सभी": true, "साथ": true, "साबुत": true, "साभ": true,
		"सारा": true, "से": true, "सो": true, "संग": true, "ही": true, "हुआ": true, "हुई": true,
		"हुए": true, "है": true, "हैं": true, "हो": true, "होता": true, "होती": true, "होते": true,
		"होना": true, "होने": true, "अब": true, "केवल": true, "शायद": true,
	}

	// Tamil stop words
	stopWordsByLanguage["TAMIL"] = map[string]bool{
		"அது": true, "அந்த": true, "அவர்": true, "அவர்கள்": true, "அவள்": true, "அவன்": true,
		"அவை": true, "ஆக": true, "ஆகிய": true, "ஆகியோர்": true, "ஆகும்": true, "ஆகையால்": true,
		"ஆதலால்": true, "ஆதலின்": true, "ஆம்": true, "ஆவது": true, "இங்கு": true, "இங்கே": true,
		"இதன்": true, "இது": true, "இந்த": true, "இப்படி": true, "இப்போது": true, "இம்": true,
		"இரு": true, "இருக்க": true, "இருக்கும்": true, "இருந்த": true, "இருந்து": true, "இல்": true,
		"இல்லை": true, "இவர்": true, "இவர்கள்": true, "இவள்": true, "இவன்": true, "இவை": true,
		"இன்று": true, "உம்": true, "உள்ள": true, "உள்ளது": true, "உள்ளன": true, "என": true,
		"எனக்": true, "எனக்கு": true, "எனவே": true, "என்": true, "என்ன": true, "என்பது": true,
		"என்று": true, "எல்லாம்": true, "ஏது": true, "ஏன்": true, "ஏனைய": true, "ஒரு": true,
		"ஒன்று": true, "கண்": true, "கள்": true, "காட்சி": true, "காரணமாக": true, "காரணம்": true,
		"கிடையாது": true, "குறித்த": true, "குறித்து": true, "கூட": true, "கூடிய": true, "கொண்ட": true,
		"கொண்டு": true, "கொள்": true, "சில": true, "சேர்ந்த": true, "தன்": true, "தனது": true,
		"தான்": true, "திரு": true, "நான்": true, "நீ": true, "நீங்கள்": true, "பட்ட": true,
		"பட்டது": true, "படி": true, "பற்றி": true, "பற்றிய": true, "பல": true, "பல்வேறு": true,
		"பின்": true, "பின்னர்": true, "போக": true, "போது": true, "போன்ற": true, "போல": true,
		"மற்றும்": true, "மட்டும்": true, "மட்டுமே": true, "மீது": true, "முதல்": true, "முழு": true,
		"மேல்": true, "மேலும்": true, "யார்": true, "வந்த": true, "வந்து": true, "வரும்": true,
		"வரை": true, "வழி": true, "வேண்டும்": true, "வேறு": true, "விட": true, "விட்டு": true,
		"ஆனால்": true, "இல்லாமல்": true, "அதனால்": true, "முன்": true,
	}

	// Telugu stop words
	stopWordsByLanguage["TELUGU"] = map[string]bool{
		"అందరూ": true, "అందుకే": true, "అందులో": true, "అంటూ": true, "అంతా": true, "అంతే": true,
		"అంతేకాదు": true, "అక్కడ": true, "అటు": true, "అదే": true, "అది": true, "అన్ని": true,
		"అప్పుడు": true, "అలా": true, "అలాగే": true, "అవి": true, "ఆ": true, "ఆమె": true,
		"ఆయన": true, "ఇంకా": true, "ఇక": true, "ఇక్కడ": true, "ఇట్లా": true, "ఇది": true,
		"ఇప్పుడు": true, "ఇలా": true, "ఇవి": true, "ఈ": true, "ఉంటాయి": true, "ఉంటుంది": true,
		"ఉంది": true, "ఉన్న": true, "ఉన్నది": true, "ఉన్నాడు": true, "ఉన్నారు": true, "ఉన్నాయి": true,
		"ఎందుకంటే": true, "ఎప్పుడు": true, "ఎలా": true, "ఎవరు": true, "ఏ": true, "ఏం": true,
		"ఏది": true, "ఏమి": true, "ఏమిటి": true, "ఒక": true, "ఒకటి": true, "కంటే": true,
		"కనుక": true, "కాకుండా": true, "కాగా": true, "కాదు": true, "కాని": true, "కాబట్టి": true,
		"కూడా": true, "గా": true, "గురించి": true, "చాలా": true, "చేస్తుంది": true, "చేసింది": true,
		"తన": true, "తను": true, "తర్వాత": true, "తో": true, "తోపాటు": true, "దాని": true,
		"దీని": true, "నందు": true, "ని": true, "ను": true, "నుంచి": true, "నుండి": true,
		"నేను": true, "పై": true, "పైన": true, "మధ్య": true, "మరియు": true, "మరొక": true,
		"మళ్లీ": true, "మాత్రమే": true, "మీ": true, "మీద": true, "మీరు": true, "మొదలు": true,
		"యొక్క": true, "రెండు": true, "లేదా": true, "లేదు": true, "లో": true, "లోని": true,
		"వద్ద": true, "వరకు": true, "వల్ల": true, "వారి": true, "వారు": true, "వాళ్ళు": true,
		"వీరు": true, "వేరే": true, "సంబంధించిన": true, "సరిగా": true, "ముందు": true, "అవునా": true,
		"అయితే": true, "అయినా": true,
	}

	// Kannada stop words
	stopWordsByLanguage["KANNADA"] = map[string]bool{
		"ಅಂದರೆ": true, "ಅಥವಾ": true, "ಅದಕ್ಕೆ": true, "ಅದನ್ನು": true, "ಅದರ": true, "ಅದು": true,
		"ಅದೇ": true, "ಅನ್ನು": true, "ಅವನ": true, "ಅವನು": true, "ಅವರ": true, "ಅವರನ್ನು": true,
		"ಅವರು": true, "ಅವಳ": true, "ಅವಳು": true, "ಅವು": true, "ಅವುಗಳ": true, "ಅವುಗಳನ್ನು": true,
		"ಅವುಗಳು": true, "ಆ": true, "ಆಗ": true, "ಆಗಿ": true, "ಆಗಿದೆ": true, "ಆದರೆ": true,
		"ಆದರೂ": true, "ಇಂದ": true, "ಇದಕ್ಕೆ": true, "ಇದನ್ನು": true, "ಇದರ": true, "ಇದು": true,
		"ಇದೇ": true, "ಇನ್ನು": true, "ಇನ್ನೂ": true, "ಇಲ್ಲ": true, "ಇಲ್ಲಿ": true, "ಇವನ": true,
		"ಇವನು": true, "ಇವರ": true, "ಇವರನ್ನು": true, "ಇವರು": true, "ಇವಳ": true, "ಇವಳು": true,
		"ಇವು": true, "ಇವುಗಳ": true, "ಇವುಗಳನ್ನು": true, "ಇವುಗಳು": true, "ಈ": true, "ಈಗ": true,
		"ಉಂಟು": true, "ಊರ": true, "ಊರಿನ": true, "ಎಂದು": true, "ಎಂಬ": true, "ಎಂಬುದನ್ನು": true,
		"ಎಂಬುದು": true, "ಎಲ್ಲ": true, "ಎಲ್ಲಾ": true, "ಎಲ್ಲಿ": true, "ಏಕೆ": true, "ಏಕೆಂದರೆ": true,
		"ಏನು": true, "ಒಂದು": true, "ಒಬ್ಬ": true, "ಒಬ್ಬನ": true, "ಒಬ್ಬರ": true, "ಒಬ್ಬಳ": true,
		"ಕಡೆ": true, "ಕಡೆಗೆ": true, "ಕೂಡ": true, "ಕೂಡಾ": true, "ಕೆಲವು": true, "ಗಳ": true,
		"ಗಳನ್ನು": true, "ಗಳು": true, "ಜೊತೆಗೆ": true, "ತನ್ನ": true, "ತಾನು": true, "ತಮ್ಮ": true,
		"ತಾವು": true, "ದಿಂದ": true, "ನನ್ನ": true, "ನನ್ನನ್ನು": true, "ನಮ್ಮ": true, "ನಮ್ಮನ್ನು": true,
		"ನಾನು": true, "ನಾವು": true, "ನಿಮ್ಮ": true, "ನಿಮ್ಮನ್ನು": true, "ನೀವು": true, "ನೀನು": true,
		"ನಂತರ": true, "ನೇ": true, "ಬಗ್ಗೆ": true, "ಬಂದ": true, "ಬಂದು": true, "ಬರುವ": true,
		"ಬಿಟ್ಟು": true, "ಮತ್ತು": true, "ಮತ್ತೆ": true, "ಮಾಡಿ": true, "ಮಾಡಿದ": true, "ಮಾಡು": true,
		"ಮಾಡುವ": true, "ಮಾತ್ರ": true, "ಮೂಲಕ": true, "ಮೇಲೆ": true, "ಯಾಕೆ": true, "ಯಾರ": true,
		"ಯಾರು": true, "ಯಾವ": true, "ಯಾವುದನ್ನು": true, "ಯಾವುದೇ": true, "ಯಾವುದು": true, "ರಂದು": true,
		"ರಲ್ಲಿ": true, "ರಿಂದ": true, "ವನ್ನು": true, "ವರೆಗೆ": true, "ವಾಗಿ": true, "ವು": true,
		"ವೇಳೆ": true, "ಸಹ": true, "ಸಾಧ್ಯ": true, "ಹಾಗೂ": true, "ಹಾಗೆ": true, "ಹೀಗೆ": true,
		"ಹೊಂದಿದೆ": true, "ಹೊಂದಿವೆ": true, "ಹೇಗೆ": true, "ಹೌದು": true,
	}

	// Malayalam stop words
	stopWordsByLanguage["MALAYALAM"] = map[string]bool{
		"അങ്ങനെ": true, "അത്": true, "അതിനാൽ": true, "അതിന്": true, "അതിന്റെ": true, "അതു": true,
		"അതും": true, "അതെ": true, "അതേ": true, "അദ്ദേഹം": true, "അദ്ദേഹത്തിന്റെ": true, "അപ്പോൾ": true,
		"അല്ല": true, "അല്ലാത്ത": true, "അല്ലാതെ": true, "അല്ലെങ്കിൽ": true, "അവ": true, "അവന്": true,
		"അവന്റെ": true, "അവൻ": true, "അവയുടെ": true, "അവയെ": true, "അവയ്ക്ക്": true, "അവർ": true,
		"അവരുടെ": true, "അവരെ": true, "അവർക്ക്": true, "അവളുടെ": true, "അവളെ": true, "അവൾ": true,
		"അവൾക്ക്": true, "ആ": true, "ആണ്": true, "ആയ": true, "ആയി": true, "ആയിരുന്നു": true,
		"ആരുടെ": true, "ആരെ": true, "ആർ": true, "ആർക്ക്": true, "ഇങ്ങനെ": true, "ഇത്": true,
		"ഇതിനാൽ": true, "ഇതിന്": true, "ഇതിന്റെ": true, "ഇതു": true, "ഇതും": true, "ഇതെ": true,
		"ഇതേ": true, "ഇനി": true, "ഇന്ന്": true, "ഇപ്പോൾ": true, "ഇല്ല": true, "ഇല്ലാത്ത": true,
		"ഇവ": true, "ഇവയുടെ": true, "ഇവയെ": true, "ഇവയ്ക്ക്": true, "ഇവിടെ": true, "ഈ": true,
		"ഉണ്ട്": true, "ഉണ്ടായി": true, "ഉണ്ടായിരുന്നു": true, "ഉം": true, "ഉള്ള": true, "ഉള്ളത്": true,
		"എങ്കിൽ": true, "എങ്കിലും": true, "എങ്ങനെ": true, "എന്ത്": true, "എന്തുകൊണ്ട്": true, "എന്ന": true,
		"എന്നത്": true, "എന്നാൽ": true, "എന്നിട്ടും": true, "എന്നു": true, "എന്നും": true, "എന്ന്": true,
		"എല്ലാ": true, "എല്ലാം": true, "എവിടെ": true, "ഏത്": true, "ഏതു": true, "ഏതെങ്കിലും": true,
		"ഏതെല്ലാം": true, "ഒരു": true, "ഒന്ന്": true, "ഒന്നും": true, "കാരണം": true, "കീഴിൽ": true,
		"കുറിച്ച്": true, "കൂടാതെ": true, "കൂടി": true, "കൂടുതൽ": true, "കൊണ്ട്": true, "ചെയ്ത": true,
		"ചെയ്യാൻ": true, "ചെയ്യുന്ന": true, "ചെയ്യുന്നത്": true, "ചേർന്ന്": true, "ചില": true, "തന്നെ": true,
		"തന്റെ": true, "താൻ": true, "താഴെ": true, "തിരിച്ച്": true, "നല്ല": true, "നിങ്ങൾ": true,
		"നിങ്ങളുടെ": true, "നിന്ന്": true, "നിന്നു": true, "നിന്നും": true, "നോക്കി": true, "പക്ഷേ": true,
		"പല": true, "പോലെ": true, "മാത്രം": true, "മാത്രമല്ല": true, "മുകളിൽ": true, "മുതൽ": true,
		"മുൻപ്": true, "മേൽ": true, "യാതൊരു": true, "രണ്ട്": true, "വരെ": true, "വളരെ": true,
		"വഴി": true, "വിവിധ": true, "വീണ്ടും": true, "വേണം": true, "വേണ്ട": true, "വേണ്ടി": true,
		"ശേഷം": true, "സംബന്ധിച്ച്": true,
	}

	// Bengali stop words
	stopWordsByLanguage["BENGALI"] = map[string]bool{
		"অতএব": true, "অথচ": true, "অথবা": true, "অনুযায়ী": true, "অনেক": true, "অনেকে": true,
		"অনেকেই": true, "অন্তত": true, "অবধি": true, "অবশ্য": true, "অর্থাৎ": true, "আই": true,
		"আগামী": true, "আগে": true, "আজ": true, "আদ্যভাগে": true, "আপনার": true, "আপনি": true,
		"আবার": true, "আমরা": true, "আমাকে": true, "আমাদের": true, "আমার": true, "আমি": true,
		"আর": true, "আরও": true, "ই": true, "ইত্যাদি": true, "ইহা": true, "উচিত": true, "উত্তর": true,
		"উনি": true, "উপর": true, "উপরে": true, "এ": true, "এই": true, "এক": true, "একই": true,
		"একটি": true, "একটা": true, "একটু": true, "একে": true, "এখন": true, "এখনও": true, "এখানে": true, "এখানেই": true, "এটা": true,
		"এটাই": true, "এটি": true, "এত": true, "এতে": true, "এদের": true, "এব": true, "এবং": true,
		"এবার": true, "এমন": true, "এমনকি": true, "এমনি": true, "এর": true, "এরা": true, "এল": true,
		"এস": true, "এসে": true, "ঐ": true, "ও": true, "ওই": true, "ওকে": true, "ওখানে": true,
		"ওদের": true, "ওনা": true, "ওনার": true, "ওনাদের": true, "ওর": true, "ওরা": true, "কখনও": true,
		"কত": true, "কবে": true, "কম": true, "কয়েক": true, "কয়েকটি": true, "করছে": true, "করছেন": true,
		"করতে": true, "করবে": true, "করবেন": true, "করলে": true, "করলেন": true, "করা": true, "করায়": true,
		"করার": true, "করি": true, "করিতে": true, "করিয়া": true, "করিয়াছে": true, "করে": true,
		"করেছিলেন": true, "করেছে": true, "করেছেন": true, "করেন": true, "কাউকে": true, "কাছ": true,
		"কাছে": true, "কাজ": true, "কাজে": true, "কারও": true, "কারণ": true, "কি": true, "কিংবা": true,
		"কিছু": true, "কিছুই": true, "কিন্তু": true, "কী": true, "কে": true, "কেউ": true, "কেউই": true,
		"কেন": true, "কেমন": true, "কোটি": true, "কোন": true, "কোনও": true, "কোনো": true, "ক্ষেত্রে": true,
		"খুব": true, "খুবই": true, "গিয়ে": true, "গিয়েছে": true, "গুলি": true, "গেছে": true, "গেল": true,
		"গেলে": true, "গোটা": true, "চলে": true, "চান": true, "চায়": true, "চার": true, "চালু": true,
		"চেয়ে": true, "চেষ্টা": true, "ছাড়া": true, "ছাড়াও": true, "ছিল": true, "ছিলেন": true, "জন": true,
		"জনকে": true, "জনের": true, "জন্য": true, "জন্যই": true, "জানতে": true, "জানা": true, "জানানো": true,
		"জানায়": true, "জানিয়ে": true, "জানিয়েছে": true, "জে": true, "জ্ঞ": true, "টি": true, "ঠিক": true,
		"তখন": true, "তত": true, "তথা": true, "তবু": true, "তবুও": true, "তবে": true, "তা": true,
		"তাঁকে": true, "তাঁদের": true, "তাঁর": true, "তাঁরা": true, "তাঁাহারা": true, "তাই": true, "তাও": true,
		"তাকে": true, "তাতে": true, "তাদের": true, "তার": true, "তারপর": true, "তারা": true, "তারই": true,
		"তাহলে": true, "তাহা": true, "তাহাতে": true, "তাহার": true, "তিনঐ": true, "তিনি": true, "তুমি": true,
		"তুলে": true, "তেমন": true, "তো": true, "তোমার": true, "থাকবে": true, "থাকবেন": true, "থাকা": true,
		"থাকায়": true, "থাকার": true, "থাকে": true, "থাকেন": true, "থেকে": true, "থেকেই": true, "থেকেও": true,
		"দিকে": true, "দিতে": true, "দিন": true, "দিয়ে": true, "দিয়েছে": true, "দিয়েছেন": true, "দিলেন": true,
		"দু": true, "দুই": true, "দুটি": true, "দুটো": true, "দেওয়া": true, "দেওয়ার": true,
		"দেখতে": true, "দেখা": true, "দেখে": true, "দেন": true, "দেয়": true, "দেশ": true, "দ্বারা": true,
		"ধরা": true, "ধরে": true, "ধামার": true, "নতুন": true, "নয়": true, "না": true, "নাই": true,
		"নাকি": true, "নাগাদ": true, "নানা": true, "নিজে": true, "নিজেই": true, "নিজেদের": true, "নিজের": true,
		"নিতে": true, "নিয়ে": true, "নেই": true, "নেওয়া": true, "নেওয়ার": true,
		"পক্ষে": true, "পর": true, "পরই": true, "পরে": true, "পরেই": true, "পরের": true,
		"পর্যন্ত": true, "পাওয়া": true, "পাচ": true, "পারি": true, "পারে": true, "পারেন": true, "পি": true,
		"পেয়ে": true, "পেয়্র্": true, "প্রতি": true, "প্রথম": true, "প্রভাব": true, "প্রভৃতি": true, "প্রয়োজন": true,
		"প্রাথমিক": true, "প্রায়": true, "ফলে": true, "ফিরে": true, "ফের": true, "বক্তব্য": true,
		"বদলে": true, "বন": true, "বরং": true, "বলতে": true, "বলল": true, "বললেন": true, "বলা": true,
		"বলায়": true, "বলার": true, "বলি": true, "বলে": true, "বলেছেন": true, "বলেন": true, "বসে": true,
		"বহু": true, "বা": true, "বাদে": true, "বার": true, "বি": true, "বিনা": true, "বিভিন্ন": true,
		"বিশেষ": true, "বিষয়টি": true, "বেশ": true, "বেশি": true, "ব্যবহার": true, "ব্যাপারে": true, "ভাবে": true,
		"ভাবেই": true, "মতো": true, "মতোই": true, "মধ্যভাগে": true, "মধ্যে": true, "মধ্যেই": true, "মধ্যেও": true,
		"মনে": true, "মাত্র": true, "মাধ্যমে": true, "মোট": true, "মোটেই": true, "মোদের": true, "মোরা": true,
		"যখন": true, "যত": true, "যতটা": true, "যথেষ্ট": true, "যদি": true, "যদিও": true, "যা": true,
		"যাঁর": true, "যাঁরা": true, "যাওয়া": true, "যাওয়ার": true, "যাকে": true, "যাচ্ছে": true,
		"যাতে": true, "যাদের": true, "যান": true, "যাবে": true, "যায়": true, "যার": true, "যারা": true,
		"যিনি": true, "যে": true, "যেখানে": true, "যেতে": true, "যেন": true, "যেমন": true, "রকম": true,
		"রয়েছে": true, "রাখা": true, "রেখে": true, "লক্ষ": true, "শুধু": true, "শুরু": true, "সঙ্গে": true,
		"সঙ্গেও": true, "সব": true, "সবাই": true, "সমস্ত": true, "সময়": true, "সহ": true, "সাধারণ": true,
		"সামনে": true, "সি": true, "সুতরাং": true, "সে": true, "সেই": true, "সেখান": true, "সেখানে": true,
		"সেটা": true, "সেটাই": true, "সেটাও": true, "সেটি": true, "সেরকম": true, "সেসব": true, "স্পষ্ট": true,
		"স্বয়ং": true, "হইতে": true, "হইবে": true, "হইয়া": true, "হওয়া": true, "হওয়ায়": true, "হওয়ার": true,
		"হচ্ছে": true, "হত": true, "হতে": true, "হতেই": true, "হন": true, "হবে": true, "হবেন": true,
		"হয়": true, "হয়তো": true, "হয়নি": true, "হয়ে": true, "হয়েই": true, "হয়েছিল": true, "হয়েছে": true,
		"হয়েছেন": true, "হল": true, "হলে": true, "হলেই": true, "হলেও": true, "হলো": true, "হাজার": true,
		"হিসাবে": true, "হৈলে": true, "হোক": true,
	}

	// Marathi stop words
	stopWordsByLanguage["MARATHI"] = map[string]bool{
		"अधिक": true, "अनेक": true, "अशी": true, "असलयाचे": true, "असलेल्या": true, "असा": true,
		"असून": true, "असे": true, "आज": true, "आणि": true, "आता": true, "आपल्या": true,
		"आम्हांला": true, "आम्ही": true, "आहे": true, "आहेत": true, "एक": true, "एका": true,
		"कमी": true, "करणयात": true, "करून": true, "का": true, "काम": true, "काय": true,
		"काही": true, "किंवा": true, "की": true, "केला": true, "केली": true, "केले": true,
		"कोणता": true, "कोणती": true, "कोणते": true, "गेल्या": true, "घेऊन": true, "जात": true,
		"झाला": true, "झाली": true, "झाले": true, "झालेल्या": true, "टा": true, "डॉ": true,
		"तर": true, "तरी": true, "तसेच": true, "ता": true, "ती": true, "तीन": true, "ते": true,
		"तो": true, "त्या": true, "त्याचा": true, "त्याची": true, "त्याच्या": true, "त्याना": true,
		"त्याने": true, "त्यामुळे": true, "त्री": true, "दिली": true, "दोन": true, "न": true,
		"नाही": true, "निर्ण्य": true, "पण": true, "पम": true, "परंतु": true, "पाटील": true,
		"म": true, "मात्र": true, "माहिती": true, "मी": true, "मुबी": true, "म्हणजे": true,
		"म्हणाले": true, "म्हणून": true, "या": true, "याचा": true, "याची": true, "याच्या": true,
		"याना": true, "यानी": true, "येणार": true, "येत": true, "येथील": true, "येथे": true,
		"लाख": true, "व": true, "व्यकत": true, "सर्व": true, "सागित्ले": true, "सुरू": true,
		"हजार": true, "हा": true, "ही": true, "हे": true, "होणार": true, "होत": true, "होता": true,
		"होती": true, "होते": true, "ह्या": true,
	}

	// Gujarati stop words
	stopWordsByLanguage["GUJARATI"] = map[string]bool{
		"અંગે": true, "અત્રે": true, "અથવા": true, "અને": true, "અમને": true, "અમારા": true,
		"અમારી": true, "અમારે": true, "અમે": true, "અહીં": true, "આ": true, "આગળ": true,
		"આજે": true, "આથી": true, "આપ": true, "આપણને": true, "આપણા": true, "આપણી": true,
		"આપણે": true, "આમ": true, "આવી": true, "આવે": true, "આવ્યા": true, "આવ્યો": true,
		"ઉપર": true, "એ": true, "એક": true, "એટલે": true, "એની": true, "એના": true, "એનું": true,
		"એને": true, "એનો": true, "એમ": true, "એમણે": true, "એમને": true, "એમનું": true, "એમના": true,
		"એમની": true, "એમાં": true, "એવી": true, "એવું": true, "એવા": true, "એવો": true, "ઓછા": true,
		"કંઈ": true, "કઈ": true, "કયા": true, "કયું": true, "કયો": true, "કરી": true, "કરે": true,
		"કરેલ": true, "કરો": true, "કર્યા": true, "કર્યું": true, "કર્યો": true, "કર્યાં": true,
		"કરવા": true, "કરવી": true, "કરવું": true, "કરશે": true, "કરશો": true, "કરાય": true,
		"કરીએ": true, "કરીને": true, "કરું": true,
		"કહે": true, "કહેવાય": true, "કહ્યું": true, "કાં": true, "કારણ": true, "કે": true, "કેટલા": true,
		"કેટલી": true, "કેટલું": true, "કેમ": true, "કેવી": true, "કેવું": true, "કેવા": true,
		"કેવો": true, "કોઈ": true, "કોઈક": true, "કોણ": true, "કોને": true, "ક્યાં": true,
		"ક્યારે": true, "ખૂબ": true, "ગઈ": true, "ગયા": true, "ગયું": true, "ગયો": true, "ઘણા": true,
		"ઘણી": true, "ઘણું": true, "છું": true, "છે": true, "છો": true, "છીએ": true, "જ": true,
		"જે": true, "જેઓ": true, "જેથી": true, "જેને": true, "જેમ": true, "જેવી": true, "જેવું": true,
		"જેવા": true, "જેવો": true, "જો": true, "જોઈએ": true, "જોઈતી": true, "જોઈતું": true,
		"જોઈતા": true, "જોઈતો": true, "જોકે": true, "જ્યાં": true, "જ્યારે": true, "ઝાઝા": true,
		"ઝાઝી": true, "ઝાઝું": true, "તથા": true, "તમને": true, "તમારા": true, "તમારી": true,
		"તમારું": true, "તમારે": true, "તમે": true, "તરત": true, "તરીકે": true, "તા": true,
		"તેં": true, "તે": true, "તેઓ": true, "તેણી": true, "તેણે": true, "તેથી": true, "તેના": true,
		"તેની": true, "તેનું": true, "તેને": true, "તેનો": true, "તેમ": true, "તેમજ": true,
		"તેમણે": true, "તેમના": true, "તેમની": true, "તેમનું": true, "તેમને": true, "તેમનો": true,
		"તેમાં": true, "તેવી": true, "તેવું": true, "તેવા": true, "તેવો": true, "તો": true,
		"ત્યાં": true, "ત્યારે": true, "થઈ": true, "થતા": true, "થતી": true, "થતું": true,
		"થયા": true, "થયું": true, "થયેલ": true, "થયો": true, "થવા": true, "થવી": true, "થવું": true,
		"થશે": true, "થાઓ": true, "થાય": true, "થી": true, "થોડા": true, "થોડી": true, "થોડું": true,
		"દર": true, "દરેક": true, "ન": true, "નથી": true, "નહિ": true, "નહીં": true, "ના": true,
		"ની": true, "નીચે": true, "નું": true, "ને": true, "નો": true, "પછી": true, "પણ": true,
		"પર": true, "પરંતુ": true, "પહેલાં": true, "પાછળ": true, "પાસે": true, "પોતાના": true,
		"પોતાની": true, "પોતાનું": true, "પોતાને": true, "પોતાનો": true, "પોતે": true, "પ્રત્યેક": true,
		"પ્રમાણે": true, "ફરી": true, "બધા": true, "બધી": true, "બધું": true, "બની": true, "બને": true,
		"બન્ને": true, "બહુ": true, "બાદ": true, "બીજા": true, "બીજી": true, "બીજું": true,
		"ભલે": true, "મને": true, "મા": true, "માં": true, "માટે": true, "મારા": true, "મારી": true,
		"મારું": true, "મારે": true, "માત્ર": true, "મેં": true, "મોટા": true, "મોટી": true,
		"મોટું": true, "યા": true, "રહી": true, "રહે": true, "રહેલ": true, "રહ્યા": true,
		"રહ્યું": true, "રહ્યો": true, "રીતે": true, "વગેરે": true, "વધારે": true, "વધુ": true,
		"વાર": true, "વિશે": true, "વિષે": true, "શકાય": true, "શકે": true, "શક્ય": true, "શા": true,
		"શી": true, "શું": true, "સરખા": true, "સરખી": true, "સરખું": true, "સાથે": true, "સામે": true,
		"સારી": true, "સારું": true, "સારા": true, "સારો": true, "સૌ": true, "સૌથી": true,
		"હતા": true, "હતી": true, "હતું": true, "હતો": true, "હવે": true, "હશે": true, "હા": true,
		"હું": true, "હોઈ": true, "હોઈશ": true, "હોત": true, "હોય": true, "હોવા": true, "હોવી": true,
		"હોવું": true,
	}

	// Odia stop words
	stopWordsByLanguage["ODIA"] = map[string]bool{
		"ଅଛି": true, "ଅଟନ୍ତି": true, "ଅଟେ": true, "ଅଥବା": true, "ଅନେକ": true, "ଅନ୍ୟ": true,
		"ଅନ୍ୟାନ୍ୟ": true, "ଅବଶ୍ୟ": true, "ଅଧିକ": true, "ଅଧିକାଂଶ": true, "ଆଉ": true, "ଆଜି": true,
		"ଆଦି": true, "ଆପଣ": true, "ଆପଣଙ୍କ": true, "ଆପଣଙ୍କର": true, "ଆପଣମାନେ": true, "ଆମ": true,
		"ଆମକୁ": true, "ଆମର": true, "ଆମେ": true, "ଆମ୍ଭେ": true, "ଆମ୍ଭେମାନେ": true, "ଇତ୍ୟାଦି": true,
		"ଉଚିତ": true, "ଉପରେ": true, "ଏଇ": true, "ଏକ": true, "ଏକାଧିକ": true, "ଏଠାରେ": true,
		"ଏଠାରୁ": true, "ଏଠି": true, "ଏଣିକି": true, "ଏତେ": true, "ଏପରି": true, "ଏପରିକି": true,
		"ଏବଂ": true, "ଏବେ": true, "ଏମିତି": true, "ଏହା": true, "ଏହାକୁ": true, "ଏହାଦ୍ୱାରା": true,
		"ଏହାପରେ": true, "ଏହାର": true, "ଏହି": true, "ଏହିପରି": true, "ଓ": true, "କଣ": true, "କରନ୍ତି": true,
		"କରାଯାଇଛି": true, "କରାଯାଉଛି": true, "କରାଯିବ": true, "କରି": true, "କରିଛନ୍ତି": true, "କରିଛି": true,
		"କରିଥାଏ": true, "କରିଥିଲା": true, "କରିଥିଲେ": true, "କରିବ": true, "କରିବା": true, "କରିବାକୁ": true,
		"କରିବାର": true, "କରିବେ": true, "କରୁଛନ୍ତି": true, "କରୁଛି": true, "କରୁଥିବା": true, "କରୁଥିଲା": true,
		"କରୁଥିଲେ": true, "କରେ": true, "କହନ୍ତି": true, "କହିଛନ୍ତି": true, "କହିଥିଲେ": true, "କହିଲେ": true,
		"କାରଣ": true, "କି": true, "କିଛି": true, "କିନ୍ତୁ": true, "କିପରି": true, "କିମ୍ବା": true,
		"କିଏ": true, "କୁ": true, "କୁହାଯାଇଛି": true, "କୁହାଯାଏ": true, "କୁହାଯାଉଛି": true, "କୁହନ୍ତି": true,
		"କେଉଁ": true, "କେଉଁଠାରେ": true, "କେଉଁଠି": true, "କେଉଁମାନେ": true, "କେତେ": true, "କେତେକ": true,
		"କେବଳ": true, "କେମିତି": true, "କେହି": true, "କୌଣସି": true, "ଖୁବ": true, "ଖୁବ୍": true,
		"ଗୋଟିଏ": true, "ଗୋଟେ": true, "ଘଟଣା": true, "ଚାଲିଛି": true, "ଛି": true, "ଜଣ": true,
		"ଜଣକ": true, "ଜଣେ": true, "ଜାଣନ୍ତି": true, "ଜାଣିଛନ୍ତି": true, "ଜେ": true, "ଟି": true,
		"ତଥା": true, "ତଥାପି": true, "ତହିଁରେ": true, "ତାଙ୍କ": true, "ତାଙ୍କର": true, "ତାଙ୍କୁ": true,
		"ତାହା": true, "ତାହାକୁ": true, "ତାହାର": true, "ତୁମ": true, "ତୁମକୁ": true, "ତୁମର": true,
		"ତୁମେ": true, "ତୁମ୍ଭ": true, "ତୁମ୍ଭକୁ": true, "ତୁମ୍ଭର": true, "ତୁମ୍ଭେ": true, "ତେଣୁ": true,
		"ତେବେ": true, "ଥାଇପାରେ": true, "ଥାଏ": true, "ଥିବା": true, "ଥିବାର": true, "ଥିଲା": true,
		"ଥିଲେ": true, "ଦରକାର": true, "ଦାବି": true, "ଦିଆଯାଇଛି": true, "ଦିଆଯାଉଛି": true, "ଦିଏ": true,
		"ଦୁଇ": true, "ଦୁଇଟି": true, "ଦେଇ": true, "ଦେଇଛନ୍ତି": true, "ଦେଖାଯାଇଛି": true, "ଦେଖାଯାଏ": true,
		"ଦେଖାଯାଉଛି": true, "ଦେଖିବାକୁ": true, "ଦେବ": true, "ଦ୍ୱାରା": true, "ଧରି": true, "ନଥିବା": true, "ନଥିଲା": true, "ନଥିଲେ": true,
		"ନଦେଇ": true, "ନା": true, "ନାହିଁ": true, "ନିଜ": true, "ନିଜକୁ": true, "ନିଜର": true,
		"ନିଜେ": true, "ନିମନ୍ତେ": true, "ନିମିତ୍ତ": true, "ନିଶ୍ଚିତ": true, "ନୁହଁନ୍ତି": true,
		"ନୁହଁ": true, "ନୁହେଁ": true, "ନେଇ": true, "ପକ୍ଷରୁ": true, "ପଡିଛି": true, "ପରି": true,
		"ପରେ": true, "ପାଇଁ": true, "ପାଇଥିବା": true, "ପାଖରେ": true, "ପାରନ୍ତି": true, "ପାରିବ": true,
		"ପାରିବେ": true, "ପାରେ": true, "ପୂର୍ବରୁ": true, "ପ୍ରକାର": true, "ପ୍ରତି": true, "ପ୍ରତ୍ୟେକ": true,
		"ପ୍ରଥମ": true, "ପ୍ରଦାନ": true, "ପ୍ରାୟ": true, "ବରଂ": true, "ବହୁ": true, "ବହୁତ": true,
		"ବା": true, "ବି": true, "ବିଭିନ୍ନ": true, "ବିଶେଷ": true, "ବିଷୟରେ": true, "ବୋଲି": true,
		"ଭଳି": true, "ଭଳିଆ": true, "ଭାବରେ": true, "ଭାବେ": true, "ଭିତରେ": true, "ମଧ୍ୟ": true,
		"ମଧ୍ୟରେ": true, "ମାତ୍ର": true, "ମାନେ": true, "ମାନଙ୍କ": true, "ମାନଙ୍କର": true, "ମାନଙ୍କୁ": true,
		"ମୁଁ": true, "ମୋ": true, "ମୋତେ": true, "ମୋର": true, "ଯଦି": true, "ଯଦିଓ": true, "ଯାଇଛି": true,
		"ଯାଇଥିବା": true, "ଯାଇଥିଲା": true, "ଯାଇପାରେ": true, "ଯାଉଛି": true, "ଯାଏ": true, "ଯାହା": true,
		"ଯାହାକୁ": true, "ଯାହାର": true, "ଯିଏ": true, "ଯୁକ୍ତ": true, "ଯେ": true, "ଯେଉଁ": true,
		"ଯେଉଁଠାରେ": true, "ଯେଉଁଠି": true, "ଯେଉଁମାନେ": true, "ଯେକୌଣସି": true, "ଯେତେ": true,
		"ଯେତେବେଳେ": true, "ଯେପରି": true, "ଯେପରିକି": true, "ଯେମିତି": true, "ଯେହେତୁ": true,
		"ଯୋଗୁଁ": true, "ରହିଛି": true, "ରହିଥିବା": true, "ରହିଥିଲା": true, "ରହିବ": true, "ରୂପେ": true,
		"ରେ": true, "ଲାଗି": true, "ଲାଗିଛି": true, "ଲେଖାଏଁ": true, "ଶହ": true, "ସଂପର୍କରେ": true,
		"ସକାଶେ": true, "ସବୁ": true, "ସବୁଠାରୁ": true, "ସମସ୍ତ": true, "ସମସ୍ତେ": true, "ସମୟରେ": true,
		"ସମ୍ପର୍କରେ": true, "ସମ୍ବନ୍ଧରେ": true, "ସର୍ବଦା": true, "ସହ": true, "ସହିତ": true, "ସାଙ୍ଗକୁ": true,
		"ସାରା": true, "ସେ": true, "ସେଇଠି": true, "ସେଠାକାର": true, "ସେଠାରେ": true, "ସେଠାରୁ": true,
		"ସେଠି": true, "ସେଥିପାଇଁ": true, "ସେଥିରେ": true, "ସେପରି": true, "ସେମାନଙ୍କ": true, "ସେମାନଙ୍କର": true,
		"ସେମାନଙ୍କୁ": true, "ସେମାନେ": true, "ସେମିତି": true, "ସେହି": true, "ସେହିପରି": true, "ହଜାର": true,
		"ହେଉଛନ୍ତି": true, "ହେଉଛି": true, "ହେବ": true, "ହେବା": true, "ହେବାକୁ": true, "ହେବାର": true,
		"ହେଲା": true, "ହେଲେ": true, "ହୁଅନ୍ତି": true, "ହୁଏ": true, "ହୋଇଛି": true, "ହୋଇଥାଏ": true,
		"ହୋଇଥିବା": true, "ହୋଇଥିଲା": true, "ହୋଇପାରିବ": true, "ହୋଇପାରେ": true,
	}

	// Punjabi stop words
	stopWordsByLanguage["PUNJABI"] = map[string]bool{
		"ਅਜਿਹਾ": true, "ਅਤੇ": true, "ਅੱਗੇ": true, "ਆਉਣਾ": true, "ਆਉਂਦਾ": true, "ਆਉਂਦੀ": true,
		"ਆਦਿ": true, "ਆਪ": true, "ਆਪਣਾ": true, "ਆਪਣੀ": true, "ਆਪਣੇ": true, "ਆਮ": true,
		"ਇਸ": true, "ਇਸਦਾ": true, "ਇਸਦੀ": true, "ਇਸਦੇ": true, "ਇਸਨੂੰ": true, "ਇਸਨੇ": true,
		"ਇਸਤਰਾਂ": true, "ਇਸੇ": true, "ਇਹ": true, "ਇਹਨਾਂ": true, "ਇਹੋ": true, "ਇੱਕ": true,
		"ਇੱਥੇ": true, "ਇੱਥੋਂ": true, "ਈ": true, "ਉਸ": true, "ਉਸਦਾ": true, "ਉਸਦੀ": true,
		"ਉਸਦੇ": true, "ਉਸਨੂੰ": true, "ਉਸਨੇ": true, "ਉਸੇ": true, "ਉਹ": true, "ਉਹਨਾਂ": true,
		"ਉਹੋ": true, "ਉੱਤੇ": true, "ਉੱਥੇ": true, "ਏਸ": true, "ਐਸਾ": true, "ਓਸ": true,
		"ਓਹ": true, "ਓਹਨਾਂ": true, "ਓਹੋ": true, "ਕਈ": true, "ਕਦੇ": true, "ਕਰ": true,
		"ਕਰਕੇ": true, "ਕਰਦਾ": true, "ਕਰਦੀ": true, "ਕਰਦੇ": true, "ਕਰਨ": true, "ਕਰਨਾ": true,
		"ਕਰਨਾਂ": true, "ਕਰਨੀ": true, "ਕਰਨੇ": true, "ਕਰਾਂ": true, "ਕਰੀਏ": true, "ਕਰੋ": true,
		"ਕਾਰਨ": true, "ਕਿ": true, "ਕਿਉਂ": true, "ਕਿਉਂਕਿ": true, "ਕਿਸ": true, "ਕਿਸੇ": true,
		"ਕਿਹਾ": true, "ਕੀ": true, "ਕੀਤਾ": true, "ਕੀਤੀ": true, "ਕੀਤੇ": true, "ਕੁਝ": true,
		"ਕੁੱਝ": true, "ਕੇ": true, "ਕੋਈ": true, "ਕੌਣ": true, "ਖ਼ਿਲਾਫ਼": true, "ਖੁਦ": true,
		"ਗਈ": true, "ਗਏ": true, "ਗਿਆ": true, "ਗੱਲ": true, "ਗੱਲਾਂ": true, "ਚ": true,
		"ਚਾਹਿਦਾ": true, "ਚਾਹਿਦੀ": true, "ਚਾਹੀਦਾ": true, "ਚਾਹੀਦੀ": true, "ਚੁੱਕਾ": true,
		"ਚੁੱਕੀ": true, "ਚੁੱਕੇ": true, "ਛੱਡ": true, "ਜਦੋਂ": true, "ਜਨਾਬ": true, "ਜਰੂਰ": true,
		"ਜਰੂਰੀ": true, "ਜਾ": true, "ਜਾਂ": true, "ਜਾਂਦਾ": true, "ਜਾਂਦੀ": true, "ਜਾਂਦੇ": true,
		"ਜਾਣਾ": true, "ਜਾਣੀ": true, "ਜਾਣੇ": true, "ਜਾਵੇ": true, "ਜਿਸ": true, "ਜਿਸਦਾ": true,
		"ਜਿਸਦੀ": true, "ਜਿਸਦੇ": true, "ਜਿਸਨੂੰ": true, "ਜਿਸਨੇ": true, "ਜਿਹੜਾ": true, "ਜਿਹੜੀ": true,
		"ਜਿਹੜੇ": true, "ਜਿੰਨਾ": true, "ਜਿੰਨੀ": true, "ਜਿੰਨੇ": true, "ਜਿੱਥੇ": true, "ਜੀ": true,
		"ਜੇ": true, "ਜੇਕਰ": true, "ਜੋ": true, "ਜੋਕਿ": true, "ਟਿਕ": true, "ਟੈਗ": true,
		"ਠੀਕ": true, "ਤਕ": true, "ਤਦ": true, "ਤਰਾਂ": true, "ਤਾਂ": true, "ਤਾਕਿ": true,
		"ਤੁਸੀਂ": true, "ਤੇ": true, "ਤੇਰਾ": true, "ਤੇਰੀ": true, "ਤੇਰੇ": true, "ਤੈਨੂੰ": true,
		"ਤੋਂ": true, "ਤੰੂ": true, "ਦਾ": true, "ਦੀ": true, "ਦੀਆਂ": true, "ਦੇ": true,
		"ਦੂਜਾ": true, "ਦੂਜੀ": true, "ਦੂਜੇ": true, "ਦੋਵੇਂ": true, "ਧੰਨਵਾਦ": true, "ਨਹੀਂ": true,
		"ਨਾ": true, "ਨਾਲ": true, "ਨਾਲੇ": true, "ਨਿੱਜੀ": true, "ਨੂੰ": true, "ਨੇ": true,
		"ਨੇੜੇ": true, "ਪਰ": true, "ਪਾਸੋਂ": true, "ਪਾਸੇ": true, "ਪਿਛੋਂ": true, "ਪੂਰਾ": true,
		"ਪੂਰੀ": true, "ਪੂਰੇ": true, "ਪੈਂਦਾ": true, "ਪੈਂਦੀ": true, "ਪੈਂਦੇ": true, "ਫਿਰ": true,
		"ਫੇਰ": true, "ਬਹੁਤ": true, "ਬਾਅਦ": true, "ਬਾਕੀ": true, "ਬਾਦ": true, "ਬਾਰੇ": true,
		"ਬਿਨਾ": true, "ਬਿਨਾਂ": true, "ਬਿਲਕੁਲ": true, "ਭਾਵੇਂ": true, "ਭਿੰਨ": true, "ਮਗਰ": true,
		"ਮੈਂ": true, "ਮੈਨੂੰ": true, "ਮੇਰਾ": true, "ਮੇਰੀ": true, "ਮੇਰੇ": true, "ਯਾ": true,
		"ਯਾਨੀ": true, "ਰਹਿ": true, "ਰਹਿੰਦਾ": true, "ਰਹਿੰਦੀ": true, "ਰਹਿੰਦੇ": true, "ਰਹੇ": true,
		"ਲਈ": true, "ਲਏ": true, "ਲਗਭਗ": true, "ਲੈ": true, "ਲੈਂਦਾ": true, "ਲੈਂਦੀ": true,
		"ਲੈਂਦੇ": true, "ਵਰਗਾ": true, "ਵਰਗੀ": true, "ਵਰਗੇ": true, "ਵਰਤੋਂ": true, "ਵਲੋਂ": true,
		"ਵਾਂਗ": true, "ਵਾਂਗੂੰ": true, "ਵਾਰ": true, "ਵਾਲਾ": true, "ਵਾਲੀ": true, "ਵਾਲੇ": true,
		"ਵਾਸਤੇ": true, "ਵਿਚ": true, "ਵਿਚੋਂ": true, "ਵਿੱਚ": true, "ਵਿੱਚੋਂ": true, "ਵੀ": true,
		"ਵੇਲੇ": true, "ਸਕਦਾ": true, "ਸਕਦੀ": true, "ਸਕਦੇ": true, "ਸਕਿਆ": true, "ਸਕੇ": true,
		"ਸਨ": true, "ਸਭ": true, "ਸਭਨਾਂ": true, "ਸਮੇਂ": true, "ਸਮੇਤ": true, "ਸਰਕਾਰ": true,
		"ਸਾਡਾ": true, "ਸਾਡੀ": true, "ਸਾਡੇ": true, "ਸਾਨੂੰ": true, "ਸਾਰਾ": true, "ਸਾਰੀ": true,
		"ਸਾਰੇ": true, "ਸਿਰਫ": true, "ਸਿਰਫ਼": true, "ਸੀ": true, "ਸੇ": true, "ਹਨ": true,
		"ਹਰ": true, "ਹਾਂ": true, "ਹਾਲਾਂਕਿ": true, "ਹਿੱਸਾ": true, "ਹੀ": true, "ਹੁੰਦਾ": true,
		"ਹੁੰਦੀ": true, "ਹੁੰਦੇ": true, "ਹੁਣ": true, "ਹੁਣੇ": true, "ਹੇਠ": true, "ਹੇਠਾਂ": true,
		"ਹੈ": true, "ਹੈਂ": true, "ਹੋ": true, "ਹੋਇਆ": true, "ਹੋਈ": true, "ਹੋਏ": true,
		"ਹੋਣ": true, "ਹੋਣਾ": true, "ਹੋਵੇ": true, "ਹੋਵੇਗਾ": true, "ਹੋਵੇਗੀ": true, "ਹੋਵੇਗੇ": true,
		"ਹੋਸਕਦਾ": true, "ਹੋਸਕਦੀ": true, "ਹੋਸਕਦੇ": true,
	}
}

func GetStopWordsMap(language string) map[string]bool {
	if words, ok := stopWordsByLanguage[strings.ToUpper(language)]; ok {
		return words
	}
	return nil
}
